{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "chaos-arcade.fullname" . }}
  labels:
    {{- include "chaos-arcade.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "chaos-arcade.selectorLabels" . | nindent 6 }}
{{- end }}
