{{- if .Values.serviceAccount.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chaos-arcade.serviceAccountName" . }}
  labels:
    {{- include "chaos-arcade.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "chaos-arcade.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
---
# a clusterrolebinding
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ template "chaos-arcade.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "chaos-arcade.serviceAccountName" . }}
    namespace: {{ template ".Release.Namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "chaos-arcade.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
