{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chaos-arcade.serviceAccountName" . }}
  labels:
    {{- include "chaos-arcade.labels" . | nindent 4 }}
{{- end -}}
