name: 'helm'
description: 'A GitHub Action to run helm commands'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  helm-version:
    description: Helm version to use
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.helm-version }}
