name: e2e

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  kind-helm:
    strategy:
      matrix:
        helm-version:
          - 3.5.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Build container image
        run: |
          ./test/build.sh
          kind load docker-image test/chaos-arcade:latest
      - name: Setup Helm
        uses: ./.github/actions/helm
        with:
          helm-version: ${{ matrix.helm-version }}
      - name: Deploy
        run: ./test/deploy.sh
      - name: Run integration tests
        run: ./test/test.sh
      - name: Debug failure
        if: failure()
        run: |
          kubectl logs -l app=chaos-arcade || true
