name: Master Branch

on:
  push:
    tags:
      - '*'

jobs:

  test:
    name: Unit-Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify
        run: mvn -B clean verify -DskipTests

  artifact:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [test,artifact]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Docker Registry Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
      - name: Building Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_REF} .
      - name: Publish Docker Image
        run: docker push $REPO