name: Master Branch

on:
  push:
    tags:
      - '*'

jobs:

  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: View env
        run: echo $RELEASE_VERSION
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Maven Package
        run: mvn -B clean package
      - name: Docker Registry Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GHCR_TOKEN }} $REPO
      - name: Building Docker Image
        run: docker build -t $REPO/ryneal/chaos-arcade:latest -t $REPO/ryneal/chaos-arcade:$RELEASE_VERSION .
      - name: Publish Docker Image
        run: docker push $REPO/ryneal/chaos-arcade:latest
      - name: Publish Docker Image tag
        run: docker push $REPO/ryneal/chaos-arcade:$RELEASE_VERSION