name: Master Branch

on:
  push:
    tags:
      - '*'

jobs:

  test:
    name: Unit-Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify
        run: mvn -B clean verify -DskipTests

  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Docker Registry Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GHCR_TOKEN }} $REPO
      - name: Building Docker Image
        run: docker build -t $REPO/ryneal/chaos-arcade:latest -t $REPO/ryneal/chaos-arcade:${GITHUB_REF#refs/tags/} .
      - name: Publish Docker Image
        run: docker push $REPO